### ISSUE TITLE
Custodia Quick Start doesn't works properly

### ISSUE THREAD

**Issue by moisesguimaraes** [latchset/custodia#242]
I'm following the quick start at https://custodia.readthedocs.io/en/latest/quick.html and I'm getting the
following error:

```
(custodia) ➜  custodia git:(master) ✗ bin/custodia quick.conf 
Traceback (most recent call last):
  File "bin/custodia", line 25, in <module>
    main()
  File "bin/custodia", line 19, in main
    func = ep.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/moguimar/workspaces/secret-management/custodia/src/custodia/server/__init__.py", line 12, in <module>
    from custodia.httpd.server import HTTPServer
  File "/home/moguimar/workspaces/secret-management/custodia/src/custodia/httpd/server.py", line 17, in <module>
    from custodia.compat import parse_qs, unquote, urlparse
  File "/home/moguimar/workspaces/secret-management/custodia/src/custodia/compat.py", line 12, in <module>
    from backports import configparser
ImportError: No module named backports
```

**Steps I've done so far:**

- cloned this repo
- make egg_info
- create config file
- create log dir
- try to run `bin/custodia quick.conf`

**I have the following modules installed in my virtual env:**

asn1crypto (0.24.0)
certifi (2018.1.18)
cffi (1.11.5)
chardet (3.0.4)
configparser (3.5.0)
cryptography (2.2.1)
enum34 (1.1.6)
idna (2.6)
ipaddress (1.0.19)
jwcrypto (0.4.2)
pip (9.0.3)
pycparser (2.18)
requests (2.18.4)
setuptools (39.0.1)
six (1.11.0)
urllib3 (1.22)
wheel (0.30.0)

I'm using **pythoh 2.7.14**

**Comment by moisesguimaraes** [comment]
`python bin/custodia quick.conf` works

I think the issue is on the shebang `#!/usr/bin/python2.7` inside bin/custodia. Even being inside a virtualenv it runs with the system install of python not being able to find the dependencies I installed in the virtualenv.
