### ISSUE TITLE
FreeIPA replica install fails

### ISSUE THREAD

**Issue by tiran** [latchset/custodia#84]
```
2016-09-28T15:29:32Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 447, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 437, in run_step
    method()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/custodiainstance.py", line 97, in __import_ra_key
    cli = CustodiaClient(self.fqdn, self.master_host_name, self.realm)
  File "/usr/lib/python2.7/site-packages/ipapython/secrets/client.py", line 58, in __init__
    self.keystore = self._keystore(realm, ldap_uri, auth_type)
  File "/usr/lib/python2.7/site-packages/ipapython/secrets/client.py", line 42, in _keystore
    return iSecStore(config)
TypeError: Can't instantiate abstract class iSecStore with abstract methods span
```

**Comment by tiran** [comment]
See https://fedorahosted.org/freeipa/ticket/6365
